force-app/main/default/objects/Reporte_de_Gastos__c/Reporte_de_Gastos__c.object-meta.xml
<CustomObject>
    <label>Reporte de Gastos</label>
    <nameField>
        <label>Reporte de Gastos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reportes de Gastos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporte_de_Gastos__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En proceso</fullName>
            </value>
            <value>
                <fullName>A modificar</fullName>
            </value>
            <value>
                <fullName>Parcialmente Aprobada</fullName>
            </value>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>No aprobado</fullName>
            </value>
            <value>
                <fullName>Aprobada y cerrada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_de_Gastos__c/fields/Monto__c.field-meta.xml
<CustomField>
    <fullName>Monto__c</fullName>
    <label>Monto</label>
    <summarizedField>Factura__c.Monto_Total__c</summarizedField>
    <summaryForeignKey>Factura__c.Reporte_de_Gastos__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/GastosMayorOMenorHelper.cls
public class GastosMayorOMenorHelper {
    public static void validarMonto(List<Reporte_de_Gastos__c> listadoReportes){ 
        for (Reporte_de_Gastos__c reporte : listadoReportes){
            if(reporte.Monto__c > 200 & reporte.Estado__c == 'Parcialmente Aprobada'){
                List<EmailTemplate> listaTemplates  = [SELECT Id, Subject, Body 
                                                      FROM EmailTemplate
                                                      WHERE Id='00X1D0000018MsGUAU'];
                    
                List<User> listaUsuarios  = [SELECT Id, ProfileId, Name 
                                             FROM User
                                             WHERE ProfileId='00e1D000000O4ifQAC'];
                                        
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
				mail.setTemplateId(listaTemplates[0].Id);
                mail.setTargetObjectId(listaUsuarios[0].Id);
                mail.setSaveAsActivity(false);
                Messaging.SendEmailResult[] resultado = Messaging.SendEmail(new Messaging.SingleEmailMessage[] {mail});
            }            
        }
   }
}