force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Factura Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Monto_Total__c.field-meta.xml
<CustomField>
    <fullName>Monto_Total__c</fullName>
    <label>Monto Total</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Reporte_de_Gastos__c.field-meta.xml
<CustomField>
    <fullName>Reporte_de_Gastos__c</fullName>
    <label>Reporte de Gastos</label>
    <referenceTo>Reporte_de_Gastos__c</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reporte_de_Gastos__c/Reporte_de_Gastos__c.object-meta.xml
<CustomObject>
    <label>Reporte de Gastos</label>
    <nameField>
        <label>Reporte de Gastos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reportes de Gastos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporte_de_Gastos__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En proceso</fullName>
            </value>
            <value>
                <fullName>A modificar</fullName>
            </value>
            <value>
                <fullName>Parcialmente Aprobada</fullName>
            </value>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>No aprobado</fullName>
            </value>
            <value>
                <fullName>Aprobada y cerrada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ValidarMontoTest.cls
@isTest
private class ValidarMontoTest {
    @isTest Static Void ValidarMontoMayorTest(){
        Reporte_de_Gastos__c reporte = new Reporte_de_Gastos__c(name='testGasto',
                                                                Estado__c ='En proceso'
                                                                );
        insert reporte;
        Factura__c factura = new Factura__c (name='name',
                                                      Monto_Total__c = 250,
                                                      Reporte_de_Gastos__c = reporte.id);
                
        insert factura;
        reporte.Estado__c ='Parcialmente Aprobada';

        test.startTest();
        			upsert reporte;
                    Integer emailCalls = Limits.getEmailInvocations();
        			System.assertEquals(2, emailCalls);
        test.stopTest();      
    }
    @isTest Static Void ValidarMontoMenorTest(){
        Reporte_de_Gastos__c reporte = new Reporte_de_Gastos__c(name='testGasto',
                                                                Estado__c ='En proceso'
                                                                );
        insert reporte;
        Factura__c factura = new Factura__c (name='name',
                                                      Monto_Total__c = 100,
                                                      Reporte_de_Gastos__c = reporte.id);
        
        insert factura;
        reporte.Estado__c ='Parcialmente Aprobada';

        test.startTest();
        			upsert reporte;
                    Integer emailCalls = Limits.getEmailInvocations();
        			System.assertEquals(0, emailCalls);
        test.stopTest();      
    }
}